export const ERROR_CODES = Object.freeze({
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	NOT_FOUND: 'NOT_FOUND',
	METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	CONFLICT: 'CONFLICT',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
})
